[build]
  environment = { PYTHON_VERSION = "3.12.11" }
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"


[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200